---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: backend
  image: docker
  environment:
    USERNAME:
      from_secret: DOCKER_HUB_USERNAME
    PASSWORD:
      from_secret: DOCKER_HUB_PASSWORD
  commands:
  - sudo systemctl start docker
  - docker login -u $USERNAME -p $PASSWORD
  - docker build -t nunz9684/test-ci-project:$DRONE_BUILD_NUMBER .
  - docker push push nunz9684/test-ci-project:$DRONE_BUILD_NUMBER
  - docker tag nunz9684/test-ci-project:$DRONE_BUILD_NUMBER nunz9684/test-ci-project:latest
  - docker push nunz9684/test-ci-project:latest

trigger:
  event:
  - push