---
kind: pipeline
# type: docker
# name: default

steps:
  - name: publish
    image: plugins/docker
    environment:
      USERNAME:
        from_secret: DOCKER_HUB_USERNAME
      PASSWORD:
        from_secret: DOCKER_HUB_PASSWORD  
    username: ${USERNAME}
    password: ${PASSWORD}
    repo: nunz9684/test-ci-project:$DRONE_BUILD_NUMBER
    tag: latest
    file: Dockerfile
    when:
      branch: [master]
      event: [push]

# ---
# kind: pipeline
# type: docker
# name: default

# steps:
# - name: backend
#   image: docker
#   environment:
#     USERNAME:
#       from_secret: DOCKER_HUB_USERNAME
#     PASSWORD:
#       from_secret: DOCKER_HUB_PASSWORD
#   commands:
#   - docker login -u $USERNAME -p $PASSWORD
#   - docker build -t nunz9684/test-ci-project:$DRONE_BUILD_NUMBER .
#   - docker push nunz9684/test-ci-project:$DRONE_BUILD_NUMBER
#   - docker tag nunz9684/test-ci-project:$DRONE_BUILD_NUMBER nunz9684/test-ci-project:latest
#   - docker push nunz9684/test-ci-project:latest

# trigger:
#   event:
#   - push