---
kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: docker
  environment:
    USERNAME:
      from_secret: DOCKER_HUB_USERNAME
    PASSWORD:
      from_secret: DOCKER_HUB_PASSWORD
  commands:
  - sudo docker login -u $USERNAME -p $PASSWORD
  - sudo docker build -t nunz9684/test-ci-project:$DRONE_BUILD_NUMBER .
  - sudo docker push push nunz9684/test-ci-project:$DRONE_BUILD_NUMBER
  - sudo docker tag nunz9684/test-ci-project:$DRONE_BUILD_NUMBER nunz9684/test-ci-project:latest
  - sudo docker push nunz9684/test-ci-project:latest

trigger:
  event:
  - push